### ISSUE TITLE
Treatment of Line Breaks (addition of <br> HTML element)

### ISSUE THREAD

**Issue by z1lc** [Glutanimate/FrozenFields#11]
## Prerequisite checklist

* [✔] In case of a bug: Have you tried restarting Anki?
* [✔] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [✔] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [✔] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

Frozen Fields seems to add a line break (`<br>`) after any text that is pasted in. You can see a screenshot of what I'm talking about [here](https://i.imgur.com/xTqCbTr.png).

## How can we reproduce the problem?

1. Copy any text or image
2. Paste into any field
3. Inspect HTML of field

**Expected behavior:** Text/image is pasted in, as-is.

**Actual behavior:** Text/image is pasted in, but also includes an HTML line break element (`<br>`) at the end of the line.

**Reproducible?:** Yes, consistently. The issue goes away when I disable the Frozen Fields add-on.

## Version information

**Anki**
Version 2.1.11 (3cf770c7)
Qt 5.12.1 PyQt 5.11.3

**System**

- Operating system: Windows
- Version: 10

**Comment by glutanimate** [comment]
Thanks for the detailed report, Robert. Would you mind giving b167aaa63a0dee7fea4f67da1718729d831e8466 a try to see if it fixes the issue for you?

**Comment by z1lc** [comment]
Yep, works great! Amazingly fast turnaround, thanks Glutanimate!

**Comment by glutanimate** [comment]
Awesome! Thanks for the confirmation. New release is up now on AnkiWeb.

**Comment by glutanimate** [comment]
Reopening this as https://github.com/dae/anki/commit/4a2f39e8f4872bc276f67c236dda708b032695b2 will likely make it necessary to revert the change in FF as well.

**Comment by medshamim** [comment]
<img width="394" alt="Screen Shot 2019-05-01 at 9 09 33 PM" src="https://user-images.githubusercontent.com/47607519/57052490-7f94f800-6c55-11e9-9969-89628fe5728f.png">

Problem still persists. I tried starting Anki while holding down shift button with all addons disabled but the `<br>` is still appended. I am on 2.1.12
