### ISSUE TITLE
2.1.12 only: empty fields are too narrow 

### ISSUE THREAD

**Issue by ijgnd** [Glutanimate/FrozenFields#12]
I emptied my add-on folder today and installed Frozen Fields from Ankiweb today.
In 2.1.11 the add window looks good. 
After updating to 2.1.12 (eef86bf3 - Qt 5.12.1 PyQt 5.11.3) on Windows 10 1809 in a new profile it looks like this:

![Frozen-Fields-In-2112-2](https://user-images.githubusercontent.com/40218852/56592442-ffceb400-65ea-11e9-82bc-ced7584ad906.png)

When you enter text the height is adjusted. The functionality is not limited. It's just distracting.

**Comment by glutanimate** [comment]
Thanks for the report. This, #9, and #11 just go to show that we need to find a way to decouple the add-on from Anki's internals. I'll try to take another look at #5 soon, but if anyone has any other ideas please let me know.

In any case, I've pushed a new release that should hopefully address this: https://github.com/glutanimate/frozen-fields/releases/tag/v2.0.2

Please let me know if it works for you and I'll push it to AnkiWeb.

**Comment by glutanimate** [comment]
We're now also in the awkward position where the add-on will work fine on 2.1.x - 2.1.9, look wonky on 2.1.10-2.1.11, and look fine again on 2.1.12 onwards. Ah, I love Anki add-on development sometimes.

**Comment by ijgnd** [comment]
Thanks for the quick fix. The problem disappears with the new version. I did only a minimal test for 2.0.

P.S.:  https://github.com/Arthur-Milchior/anki-Multi-column-edit-window/commit/70f92cd5f62bd4feda5422701bd01acb41ed48ce appears to merge the multi column note editor add-on with frozen fields. I haven't checked if the code that was used from frozen field contains updates that might be interesting for this main project.

**Comment by glutanimate** [comment]
Thanks for giving the release a try! I just pushed it to AnkiWeb.

Arthur seems to be using the same method as the original FF, but I do appreciate the suggestion.
