### ISSUE TITLE
Anki 2.20 new style hook support

### ISSUE THREAD

**Issue by BlueGreenMagick** [Glutanimate/FrozenFields#13]
Other addons calling gui_hooks.editor_did_load_note does not work with this addon

**Comment by glutanimate** [comment]
Thanks again for the fix! The change is now live in [2.1.0](https://github.com/glutanimate/frozen-fields/releases/tag/v2.1.0). If you have the time, please give it a try and let me know if it works for you.

**Comment by BlueGreenMagick** [comment]
Works without issue, thanks!

**Comment by glutanimate** [comment]
Great, thanks for giving it a try! Waiting for more feedback from Arthur's users and will then be pushing the release to AnkiWeb.
