### ISSUE TITLE
Bug with resize in editer

### ISSUE THREAD

**Issue by DoctorToBeIn23** [Glutanimate/FrozenFields#16]
![Screen Shot 2020-02-20 at 4 54 51 AM](https://user-images.githubusercontent.com/60248099/74931585-22f9f980-539d-11ea-8e93-7a3a85f16ea2.jpg)

**Comment by Arthur-Milchior** [comment]
Corrected. There is little Glutanimate could have done here.
Appart from the size of the image (which should be repaired now), does everything works correctly ?

**Comment by DoctorToBeIn23** [comment]
I sent you an 8 sec video on discord. It seems like when I resize and image down to a certain point it doesn't keep the dimensions.

**Comment by Arthur-Milchior** [comment]
update. That should have been corrected

**Comment by Arthur-Milchior** [comment]
Please open different bug report, since it's not the same bug.
It's hard to find where to answer since the bug with "frozen field" has been corrected normally

**Comment by glutanimate** [comment]
OK, closing this as the FF-related issue seems to resolved upstream in Resize Image.

Thanks for the report @DoctorToBeIn23, and thanks for updating Resize Image @Arthur-Milchior.
