### ISSUE TITLE
ValueError exception in the Add window (Anki 2.1.0rc2)

### ISSUE THREAD

**Issue by ljcooke** [Glutanimate/FrozenFields#4]
## Prerequisite checklist

* [x] In case of a bug: Have you tried restarting Anki?
* [x] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [x] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [x] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

An error dialog appears when using the addon in Anki 2.1 release candidate 2. It occurs in many situations while using the Add window.

```
Anki 2.1.0rc2 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 80, in _onCmd
  File "aqt/webview.py", line 305, in _onBridgeCmd
  File "<decorator-gen-2>", line 2, in onBridgeCmd
  File "anki/hooks.py", line 66, in decorator_wrapper
  File "anki/hooks.py", line 63, in repl
  File "/Users/[…]/Library/Application Support/Anki2/addons21/frozen_fields/main.py", line 203, in onBridge
    return _old(self, str)
  File "aqt/editor.py", line 247, in onBridgeCmd
<class 'ValueError'>: invalid literal for int() with base 10: 'null'
```

## How can we reproduce the problem?

1. Open the 'Add' window to add a card.
2. Freeze or unfreeze a field.
3. Start typing in one of the fields.
4. Tab to switch to the next field.
5. Close the 'Add' window.

The error message will appear during each of steps 2–5 above.

**Expected behavior:** Add cards and freeze/unfreeze fields without interruption.

**Actual behavior:** An error message occurs repeatedly while adding a card.

**Reproducible?:** Yes

## Version information

**Anki**

Version 2.1.0rc2
Qt 5.9.2 PyQt 5.9

**System**

- Operating system: macOS
- Version: High Sierra 10.13.6

**Comment by ljcooke** [comment]
The same issue occurs in Anki2.1.0rc1. Before this I was using Anki 2.1.0 beta 37, which doesn't have this problem.

I started digging to try identifying the issue. It might be related to this change in the Anki source (dae/anki) from 30 April, commit 38178e52:

```diff
diff --git a/aqt/editor.py b/aqt/editor.py
index 7084fc4..ebd3d18 100644
--- a/aqt/editor.py
+++ b/aqt/editor.py
@@ -242,8 +242,12 @@ class Editor:
             return
         # focus lost or key/button pressed?
         if cmd.startswith("blur") or cmd.startswith("key"):
-            (type, ord, txt) = cmd.split(":", 2)
+            (type, ord, nid, txt) = cmd.split(":", 3)
             ord = int(ord)
+            nid = int(nid)
+            if nid != self.note.id:
+                print("ignored late blur")
+                return
```

**Comment by glutanimate** [comment]
Thanks for investigating this so thoroughly! Will fix this soon.

**Comment by glutanimate** [comment]
Just pushed a fix. Thanks again! I will be uploading the add-on to AnkiWeb shortly.

**Comment by ljcooke** [comment]
Awesome, thanks! Works nicely in rc2 now.
