### ISSUE TITLE
commit cf1e02e is missing from ankiweb / Uncaught ReferenceError: checkForEmptyField is not defined

### ISSUE THREAD

**Issue by ijgnd** [Glutanimate/FrozenFields#7]
Today I downloaded Frozen Fields from Ankiweb (version 2018-08-06) and used it in Anki 2.1.5.

Frozen Fields works well but for every character I type this line is output on the console `JS error on line 1: Uncaught ReferenceError: checkForEmptyField is not defined"`. 

This makes it hard to find other logging messages. 

If I apply your commit cf1e02e from 2018-08-05 this error message disappears. 

Line 104 of main.py of the version on ankiweb is still 

```js
txt += "<div id=f{0} onkeydown='onKey();' oninput='checkForEmptyField()' onmouseup='onKey();'".format(i);
```

instead of your more recent

```js
txt += "<div id=f{0} onkeydown='onKey();' oninput='onInput()' onmouseup='onKey();'".format(i);
```

**Comment by glutanimate** [comment]
Whoops! Completely forgot about pushing that update. I'll make sure to do this next week once I have more time.

Thanks for taking the time to investigate and report this!

**Comment by glutanimate** [comment]
New release is up now on AnkiWeb. Thanks again for reminding me about this, ijg, and sorry it took so long to get this published.
